import os
import datetime
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# Create a singleton Supabase client
supabase: Client = None

if SUPABASE_URL and SUPABASE_KEY:
    supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

def init_db():
    """
    Since Supabase uses Postgres which is managed via the Supabase Dashboard,
    we don't create tables via standard SQL scripts here in Python.
    
    INSTRUCTIONS FOR USER:
    1. Go to Supabase SQL Editor
    2. Run the following:
    
    CREATE TABLE users (
        user_id BIGINT PRIMARY KEY,
        username TEXT,
        trial_given BOOLEAN DEFAULT FALSE,
        first_contact TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        last_contact TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        lead_status TEXT DEFAULT 'NEW',
        last_followup TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE TABLE trial_keys (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key_value TEXT UNIQUE,
        is_used BOOLEAN DEFAULT FALSE,
        used_by BIGINT,
        used_at TIMESTAMP WITH TIME ZONE
    );
    """
    if not supabase:
        print("WARNING: SUPABASE_URL or SUPABASE_KEY is missing from .env!")
        print("Database will fail to connect.")

def log_user(user_id, username):
    if not supabase: return
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    # Check if user exists
    response = supabase.table('users').select('user_id').eq('user_id', user_id).execute()
    
    if not response.data:
        # Insert new user
        supabase.table('users').insert({
            'user_id': user_id,
            'username': username,
            'trial_given': False,
            'first_contact': now,
            'last_contact': now,
            'lead_status': 'NEW',
            'last_followup': now
        }).execute()
    else:
        # Update existing user
        supabase.table('users').update({
            'last_contact': now
        }).eq('user_id', user_id).execute()

def update_lead_status(user_id, status):
    if not supabase: return
    supabase.table('users').update({'lead_status': status}).eq('user_id', user_id).execute()

def update_last_followup(user_id):
    if not supabase: return
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    supabase.table('users').update({'last_followup': now}).eq('user_id', user_id).execute()

def get_users_for_followup(hours_threshold=24):
    if not supabase: return []
    threshold_time = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=hours_threshold)).isoformat()
    
    response = supabase.table('users').select('user_id,lead_status,username')\
        .in_('lead_status', ['INTERESTED', 'BOUGHT', 'NEW'])\
        .lt('last_followup', threshold_time)\
        .execute()
        
    return [(row['user_id'], row['lead_status'], row['username']) for row in response.data]

def get_users_for_trial_followup(hours_threshold=5):
    if not supabase: return []
    threshold_time = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=hours_threshold)).isoformat()
    
    # We want users who were given a trial more than threshold hours ago
    # and haven't received a followup yet.
    # We use trial_keys table to find when the trial was given (used_at)
    response = supabase.table('trial_keys')\
        .select('used_by, used_at')\
        .eq('is_used', True)\
        .lt('used_at', threshold_time)\
        .execute()
    
    if not response.data:
        return []

    followup_list = []
    for row in response.data:
        user_id = row['used_by']
        # Check if we already sent a followup to this user
        # (Assuming the column trial_followup_sent exists or we track it in users table)
        user_response = supabase.table('users').select('trial_followup_sent, username')\
            .eq('user_id', user_id)\
            .eq('trial_followup_sent', False)\
            .execute()
        
        if user_response.data:
            followup_list.append((user_id, user_response.data[0].get('username', 'Bhai')))
            
    return followup_list

def mark_trial_followup_sent(user_id):
    if not supabase: return
    supabase.table('users').update({'trial_followup_sent': True}).eq('user_id', user_id).execute()

def has_had_trial(user_id):
    if not supabase: return False
    response = supabase.table('users').select('trial_given').eq('user_id', user_id).execute()
    if response.data and response.data[0].get('trial_given'):
        return True
    return False

def get_available_trial_key(user_id):
    if not supabase: return "NO_KEYS_AVAILABLE"
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    # Check if they already have one
    user_resp = supabase.table('users').select('trial_given').eq('user_id', user_id).execute()
    if user_resp.data and user_resp.data[0].get('trial_given'):
        return "ALREADY_GIVEN"
        
    # Find unused key
    keys_resp = supabase.table('trial_keys').select('*').eq('is_used', False).limit(1).execute()
    if not keys_resp.data:
        return "NO_KEYS_AVAILABLE"
        
    key_row = keys_resp.data[0]
    key_val = key_row['key_value']
    
    # Mark as used in trial_keys
    supabase.table('trial_keys').update({
        'is_used': True,
        'used_by': user_id,
        'used_at': now
    }).eq('key_value', key_val).execute()
    
    # Mark user as having received a trial
    supabase.table('users').update({
        'trial_given': True
    }).eq('user_id', user_id).execute()
    
    return key_val

def add_trial_keys(keys_list):
    if not supabase: return 0
    added = 0
    for key in keys_list:
        try:
            # We must gracefully handle duplicates if the unique constraint fails
            supabase.table('trial_keys').insert({'key_value': key}).execute()
            added += 1
        except Exception:
            pass # Already exists or other duplicate error
    return added
